# Docker compose schema version
version: "3.8"

services:
  app:
    environment:
      - REACT_APP_GRAPHQL_API=https://annea-backend-service.onrender.com/graphql
    container_name: docker-annea-ui-container
    image: docker-annea-ui-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
