# Docker compose schema version
version: "3.8"

services:
  app:
    container_name: docker-annea-ui-container
    image: docker-annea-ui-image
    build:
      context: .
      args:
        REACT_APP_GRAPHQL_API: ${REACT_APP_GRAPHQL_API}
      dockerfile: Dockerfile
    ports:
      - "3000:80"
