# Configuration of jobs and pipeline related to the project config
name: Annea UI CI/CD

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
    branches: [main]

# Jobs definition with the different stage
jobs:
  build_then_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    # Sequence of tasks to execute in this job
    steps:
      # Checkout repository in your workspace (Prep to make the job access your code base)
      - name: Checkout step
        uses: actions/checkout@v4

      - uses: nelonoel/branch-name@v1.0.1
      - run: echo Running on ${BRANCH_NAME} branch

      # Node setup for the project
      - name: Use node ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}

      # Install react dependencies
      - name: Install NPM modules
        run: npm ci

      # Build the project
      - name: Build react app
        run: npm run build

      # Run the unit tests
      - name: build
        run: npm test

  # Docker steps to build the image and push it to the hub
  push_to_Docker_Hub:
    runs-on: ubuntu-latest
    needs: [build_then_test]

    steps:
      # https://github.com/docker/setup-qemu-action ( enable Support for more platforms with QEMU)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # build docker image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to Docker
      - name: Login to DockerHub account
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build & push to Docker hub
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/annea-ui:latest
          secrets: |
            "REACT_APP_GRAPHQL_API=${{secrets.REACT_APP_GRAPHQL_API}}"
            "REACT_APP_AUTHORIZATION_API_TOKEN=${{secrets.REACT_APP_AUTHORIZATION_API_TOKEN}}"

      # Run the docker image
      - name: Run image in a container
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/annea-ui:latest
          run: echo "Running the latest docker image"
